services:
  ovpn-monitor:
    build:
      context: .
    ports:
      - "9955:5000"
    volumes:
      - /run/openvpn/pt.sock:/run/openvpn/pt.sock
      - ./data:/opt/data
    environment:
      - TZ=Asia/Ho_Chi_Minh